### ISSUE TITLE
[BUG] Out of memory when using gpu on windows 10

### ISSUE THREAD

**Issue by lazytiger** [AIDungeon/AIDungeon#116]
I have a GTX 1060 gpu card, and when I run python play.py, the following log shows up:

2019-12-11 17:07:40.640433: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2019-12-11 17:07:40.699035: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library nvcuda.dll
2019-12-11 17:07:40.765668: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1618] Found device 0 with properties:
name: GeForce GTX 1060 6GB major: 6 minor: 1 memoryClockRate(GHz): 1.7085
pciBusID: 0000:01:00.0
2019-12-11 17:07:40.766209: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
2019-12-11 17:07:40.816570: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cublas64_100.dll
2019-12-11 17:07:40.862802: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cufft64_100.dll
2019-12-11 17:07:40.892844: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library curand64_100.dll
2019-12-11 17:07:40.967200: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusolver64_100.dll
2019-12-11 17:07:41.014873: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cusparse64_100.dll
2019-12-11 17:07:41.115711: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudnn64_7.dll
2019-12-11 17:07:41.117198: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1746] Adding visible gpu devices: 0
2019-12-11 17:07:41.940712: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1159] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-12-11 17:07:41.941066: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1165]      0
2019-12-11 17:07:41.941392: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1178] 0:   N
2019-12-11 17:07:41.943182: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1304] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 4848 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1060 6GB, pci bus id: 0000:01:00.0, compute capability: 6.1)
2019-12-11 17:08:37.751641: E tensorflow/stream_executor/cuda/cuda_driver.cc:893] failed to alloc 4294967296 bytes on host: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2019-12-11 17:08:37.752017: W .\tensorflow/core/common_runtime/gpu/gpu_host_allocator.h:44] could not allocate pinned host memory of size: 4294967296
2019-12-11 17:08:37.752367: E tensorflow/stream_executor/cuda/cuda_driver.cc:893] failed to alloc 3865470464 bytes on host: CUDA_ERROR_OUT_OF_MEMORY: out of memory
2019-12-11 17:08:37.752672: W .\tensorflow/core/common_runtime/gpu/gpu_host_allocator.h:44] could not allocate pinned host memory of size: 3865470464

At last, it will print stack trace as follows:
2019-12-11 17:09:09.637192: W tensorflow/core/common_runtime/bfc_allocator.cc:424] ****************************************************************************************************
Traceback (most recent call last):
  File "D:\AiDungeon2\Python\lib\site-packages\tensorflow_core\python\client\session.py", line 1365, in _do_call
    return fn(*args)
  File "D:\AiDungeon2\Python\lib\site-packages\tensorflow_core\python\client\session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "D:\AiDungeon2\Python\lib\site-packages\tensorflow_core\python\client\session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InternalError: Dst tensor is not initialized.
         [[{{node save/RestoreV2}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "play.py", line 211, in <module>
    play_aidungeon_2()
  File "play.py", line 74, in play_aidungeon_2
    generator = GPT2Generator()
  File "D:\AiDungeon2\Program\generator\gpt2\gpt2_generator.py", line 49, in __init__
    saver.restore(self.sess, ckpt)
  File "D:\AiDungeon2\Python\lib\site-packages\tensorflow_core\python\training\saver.py", line 1290, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "D:\AiDungeon2\Python\lib\site-packages\tensorflow_core\python\client\session.py", line 956, in run
    run_metadata_ptr)
  File "D:\AiDungeon2\Python\lib\site-packages\tensorflow_core\python\client\session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "D:\AiDungeon2\Python\lib\site-packages\tensorflow_core\python\client\session.py", line 1359, in _do_run
    run_metadata)
  File "D:\AiDungeon2\Python\lib\site-packages\tensorflow_core\python\client\session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InternalError: Dst tensor is not initialized.
         [[node save/RestoreV2 (defined at D:\AiDungeon2\Python\lib\site-packages\tensorflow_core\python\framework\ops.py:1748) ]]

Original stack trace for 'save/RestoreV2':
  File "play.py", line 211, in <module>
    play_aidungeon_2()
  File "play.py", line 74, in play_aidungeon_2
    generator = GPT2Generator()
  File "D:\AiDungeon2\Program\generator\gpt2\gpt2_generator.py", line 47, in __init__
    saver = tf.train.Saver()
  File "D:\AiDungeon2\Python\lib\site-packages\tensorflow_core\python\training\saver.py", line 828, in __init__
    self.build()
  File "D:\AiDungeon2\Python\lib\site-packages\tensorflow_core\python\training\saver.py", line 840, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "D:\AiDungeon2\Python\lib\site-packages\tensorflow_core\python\training\saver.py", line 878, in _build
    build_restore=build_restore)
  File "D:\AiDungeon2\Python\lib\site-packages\tensorflow_core\python\training\saver.py", line 508, in _build_internal
    restore_sequentially, reshape)
  File "D:\AiDungeon2\Python\lib\site-packages\tensorflow_core\python\training\saver.py", line 328, in _AddRestoreOps
    restore_sequentially)
  File "D:\AiDungeon2\Python\lib\site-packages\tensorflow_core\python\training\saver.py", line 575, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "D:\AiDungeon2\Python\lib\site-packages\tensorflow_core\python\ops\gen_io_ops.py", line 1696, in restore_v2
    name=name)
  File "D:\AiDungeon2\Python\lib\site-packages\tensorflow_core\python\framework\op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "D:\AiDungeon2\Python\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "D:\AiDungeon2\Python\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "D:\AiDungeon2\Python\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "D:\AiDungeon2\Python\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()

What shoud I do ?

**Comment by ruodingt** [comment]
Basically the GPT model is huge and the GPU RAM of your 1060 is not big enough. 
The cheapest way to solve this is still to use colab. 
For a paid solution you could consider get a cloud GPU or try to rent a cheap v100 at vast.ai.

**Comment by nickwalton** [comment]
You don't need a v100 you only need a K80 so that's a bit cheaper, but yeah most people don't have the specs to run this hence why we're building a hosted model
#

**Comment by nickwalton** [comment]
Hardware issue not software issue
