### ISSUE TITLE
[BUG] Numpy error

### ISSUE THREAD

**Issue by kik4444** [AIDungeon/AIDungeon#124]
**Describe the bug**
This is a continuation of the previous error from #123 
I tried manually re-installing python3.6, but now when I run the script it gives this error
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/numpy/core/__init__.py", line 17, in <module>
    from . import multiarray
  File "/usr/lib/python3.6/site-packages/numpy/core/multiarray.py", line 14, in <module>
    from . import overrides
  File "/usr/lib/python3.6/site-packages/numpy/core/overrides.py", line 7, in <module>
    from numpy.core._multiarray_umath import (
ModuleNotFoundError: No module named 'numpy.core._multiarray_umath'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "play.py", line 5, in <module>
    from generator.gpt2.gpt2_generator import *
  File "/Fast-Games/AI Dungeon 2/generator/gpt2/gpt2_generator.py", line 5, in <module>
    import numpy as np
  File "/usr/lib/python3.6/site-packages/numpy/__init__.py", line 142, in <module>
    from . import core
  File "/usr/lib/python3.6/site-packages/numpy/core/__init__.py", line 47, in <module>
    raise ImportError(msg)
ImportError: 

IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!

Importing the numpy c-extensions failed.
- Try uninstalling and reinstalling numpy.
- If you have already done that, then:
  1. Check that you expected to use Python3.6 from "/usr/bin/python3.6",
     and that you have no directories in your PATH or PYTHONPATH that can
     interfere with the Python and numpy version "1.17.3" you're trying to use.
  2. If (1) looks fine, you can open a new issue at
     https://github.com/numpy/numpy/issues.  Please include details on:
     - how you installed Python
     - how you installed numpy
     - your operating system
     - whether or not you have multiple versions of Python installed
     - if you built from source, your compiler versions and ideally a build log

- If you're working with a numpy git repository, try `git clean -xdf`
  (removes all files not under version control) and rebuild numpy.

Note: this error has many possible causes, so please don't comment on
an existing issue about this - open a new one instead.

Original error was: No module named 'numpy.core._multiarray_umath'
```
This happens when I run the script with python3.6 even with the numpy version that I had before (1.17.3). Am I missing anything else?

**Comment by kik4444** [comment]
Well something changed. I was messing around with pip and numpy and different versions of numpy for different python versions, and now that I think I finally got the right numpy, trying to start the script shows this
```
Traceback (most recent call last):
  File "/home/kiko/.local/lib/python3.6/site-packages/tensorflow_core/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/kiko/.local/lib/python3.6/site-packages/tensorflow_core/python/pywrap_tensorflow_internal.py", line 2453, in <module>
    from tensorflow.python.util import deprecation
  File "/home/kiko/.local/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 25, in <module>
    from tensorflow.python.platform import tf_logging as logging
  File "/home/kiko/.local/lib/python3.6/site-packages/tensorflow_core/python/platform/tf_logging.py", line 38, in <module>
    from tensorflow.python.util.tf_export import tf_export
  File "/home/kiko/.local/lib/python3.6/site-packages/tensorflow_core/python/util/tf_export.py", line 48, in <module>
    from tensorflow.python.util import tf_decorator
  File "/home/kiko/.local/lib/python3.6/site-packages/tensorflow_core/python/util/tf_decorator.py", line 64, in <module>
    from tensorflow.python.util import tf_stack
  File "/home/kiko/.local/lib/python3.6/site-packages/tensorflow_core/python/util/tf_stack.py", line 29, in <module>
    from tensorflow.python import _tf_stack
ImportError: /home/kiko/.local/lib/python3.6/site-packages/tensorflow_core/python/_tf_stack.so: undefined symbol: PyThread_tss_set

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "play.py", line 5, in <module>
    from generator.gpt2.gpt2_generator import *
  File "/Fast-Games/AI Dungeon 2/generator/gpt2/gpt2_generator.py", line 6, in <module>
    import tensorflow as tf
  File "/home/kiko/.local/lib/python3.6/site-packages/tensorflow/__init__.py", line 99, in <module>
    from tensorflow_core import *
  File "/home/kiko/.local/lib/python3.6/site-packages/tensorflow_core/__init__.py", line 28, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/kiko/.local/lib/python3.6/site-packages/tensorflow/__init__.py", line 50, in __getattr__
    module = self._load()
  File "/home/kiko/.local/lib/python3.6/site-packages/tensorflow/__init__.py", line 44, in _load
    module = _importlib.import_module(self.__name__)
  File "/usr/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/home/kiko/.local/lib/python3.6/site-packages/tensorflow_core/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/kiko/.local/lib/python3.6/site-packages/tensorflow_core/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/kiko/.local/lib/python3.6/site-packages/tensorflow_core/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/kiko/.local/lib/python3.6/site-packages/tensorflow_core/python/pywrap_tensorflow_internal.py", line 2453, in <module>
    from tensorflow.python.util import deprecation
  File "/home/kiko/.local/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 25, in <module>
    from tensorflow.python.platform import tf_logging as logging
  File "/home/kiko/.local/lib/python3.6/site-packages/tensorflow_core/python/platform/tf_logging.py", line 38, in <module>
    from tensorflow.python.util.tf_export import tf_export
  File "/home/kiko/.local/lib/python3.6/site-packages/tensorflow_core/python/util/tf_export.py", line 48, in <module>
    from tensorflow.python.util import tf_decorator
  File "/home/kiko/.local/lib/python3.6/site-packages/tensorflow_core/python/util/tf_decorator.py", line 64, in <module>
    from tensorflow.python.util import tf_stack
  File "/home/kiko/.local/lib/python3.6/site-packages/tensorflow_core/python/util/tf_stack.py", line 29, in <module>
    from tensorflow.python import _tf_stack
ImportError: /home/kiko/.local/lib/python3.6/site-packages/tensorflow_core/python/_tf_stack.so: undefined symbol: PyThread_tss_set


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.
```

**Comment by kik4444** [comment]
Okay it took me forever, but I think I finally managed to fix everything. It took me this long to realize that the `requirements.txt` was actually requirements for python that I could install through pip. So if anyone else sees this, here's what I did

1 - `install python36 from the AUR`
2 - `wget https://bootstrap.pypa.io/get-pip.py`
3 - `sudo python3.6 get-pip.py`       (this is to install pip into python3.6 because the default pip, if you already have it installed from the official repos, only installs files for the latest python version)
4 - `python3.6 -m pip install --user -r requirements.txt`
the final step will install all of the game's python requirements for python version 3.6 in `$HOME/.local/lib/python3.6/site-packages`. After this symlink the site-packages directory to `/usr/lib/python3.6/site-packages`. 
Finally start the game with `python3.6 play.py`
P.S. I suppose you could also do `sudo python3.6 -m pip install -r requirements.txt` to directly install everything in `/usr/lib/python3.6` and skip symlinking, but I didn't do it like that so idk if it'll be any different.

I also put it in here https://www.reddit.com/r/AIDungeon/comments/e85dx6/linux/fai5rsg?utm_source=share&utm_medium=web2x
