### ISSUE TITLE
[BUG]/[Help] No idea how to set things up; don't know if I'm doing things wrong.

### ISSUE THREAD

**Issue by Brevin630** [AIDungeon/AIDungeon#156]
So, I will be perfectly honest. I know literally nothing about coding. I barely understand html coding, so this kind of stuff is just confusing to me. I literally just found out that the way to run the game was to hit the "run all" button on Colab. 

With that being said, I don't know if I installed this correctly at all. All I did was download the torrent, and then be confused for numerous hours wondering if I need a specific program to run it in to play it locally, or even to play it at all, and I realized that I just essentially had to press the 'go' button. But, I still don't know if I'm doing things correctly. In order to run the game locally, _do_ I need some separate program? Or will it work just fine in Colab? Also, am I even doing this right? It just gives me a traceback report after, like, the 10th prompt, so I'm not sure if I set it up wrong.

If I did, can someone explain it to me in basic terms, because I monkey at this point.

Anyways, here's the traceback:

 ▄▄▄       ██▓   ▓█████▄  █    ██  ███▄    █   ▄████ ▓█████  ▒█████   ███▄    █    
▒████▄    ▓██▒   ▒██▀ ██▌ ██  ▓██▒ ██ ▀█   █  ██▒ ▀█▒▓█   ▀ ▒██▒  ██▒ ██ ▀█   █    
▒██  ▀█▄  ▒██▒   ░██   █▌▓██  ▒██░▓██  ▀█ ██▒▒██░▄▄▄░▒███   ▒██░  ██▒▓██  ▀█ ██▒   
░██▄▄▄▄██ ░██░   ░▓█▄   ▌▓▓█  ░██░▓██▒  ▐▌██▒░▓█  ██▓▒▓█  ▄ ▒██   ██░▓██▒  ▐▌██▒   
 ▓█   ▓██▒░██░   ░▒████▓ ▒▒█████▓ ▒██░   ▓██░░▒▓███▀▒░▒████▒░ ████▓▒░▒██░   ▓██░   
 ▒▒   ▓▒█░░▓      ▒▒▓  ▒ ░▒▓▒ ▒ ▒ ░ ▒░   ▒ ▒  ░▒   ▒ ░░ ▒░ ░░ ▒░▒░▒░ ░ ▒░   ▒ ▒    
  ▒   ▒▒ ░ ▒ ░    ░ ▒  ▒ ░░▒░ ░ ░ ░ ░░   ░ ▒░  ░   ░  ░ ░  ░  ░ ▒ ▒░ ░ ░░   ░ ▒░   
  ░   ▒    ▒ ░    ░ ░  ░  ░░░ ░ ░    ░   ░ ░ ░ ░   ░    ░   ░ ░ ░ ▒     ░   ░ ░    
      ░  ░ ░        ░       ░              ░       ░    ░  ░    ░ ░           ░    
                  ░                                                                

0) New Game
1) Load Game

Enter the number of your choice: 1
What is the ID of the saved game? c0281a18-1e1c-11ea-9091-0242ac1c0002
Copying gs://aidungeonstories/storyc0281a18-1e1c-11ea-9091-0242ac1c0002.json...
/ [1 files][  3.1 KiB/  3.1 KiB]                                                
Operation completed over 1 objects/3.1 KiB.                                      

Loading Game...

You are Brevin, a knight living in the kingdom of Larion. You have a steel longsword and a wooden shield. You are on a quest to defeat the evil dragon of Larion. You've heard he lives up at the north of the kingdom. You set on the path to defeat him and walk into a dark forest. As you enter the forest you see a large black dragon flying through the sky. He looks so majestic, it's almost as if he were made out of feathers.

"I'm here, I'm here!" you shout. "Let's do this"

> You look at dragon.

The dragon turns his head towards you and his eyes light up. He seems very happy that you're here. The dragon flies closer to you and lets out a roar. It sounds like an angry lion. The dragon lets out another roar and then lets out a burst of flames from his mouth

> You use shield to defend self from fire.

You raise your shield and protect yourself with it. The dragon doesn't seem to notice you, but you know he is watching you. He begins to fly higher and higher until he is about twenty feet above you. Suddenly he releases a wave of fire which engulfs you completely

> You absorb fire into your own power.

You feel heat all over your body and even on your face. Your skin burns and you scream as you burn alive

> You no you didnt.

You try to push the pain away by concentrating on the pain. You can see the dragon's face now through the smoke and flames. You don't want to die so you focus on the dragon and ignore the pain

> You jump at dragon and stab him in the eyes.

You leap at the dragon and grab his arm. You pull hard and the dragon lets go of you. You swing your sword and hit the dragon square in the eye causing him to let go of you. You run back up to the castle and tell everyone what happened

> You wait.

You wait for the dragon to come back down and attack again. Eventually he does and this time he attacks faster than before. You dodge his first two attacks and then you run up to him and slash his neck. You hear the sound of blood splashing onto the ground and the dragon falls dead

> You put dragon corpse in inventory.

You pick up the dragon corpse and put it in your inventory. You quickly look around and find some gold coins on the floor. You also find a ring and a necklace. You take them and put them in your inventory

> You look around.

You walk around the room looking for something else. You find a small chest containing a few gems and a silver ring. You put everything in your inventory and open the chest. Inside you find a ring made of pure white sapphires. You put it on and suddenly you feel much better

> You examine ring.

You put the ring on and immediately feel much happier. You think you might be dying soon, but now you feel much better. You continue to wear the ring and enjoy life.
 
> Walk around town
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: 2 root error(s) found.
  (0) Resource exhausted: OOM when allocating tensor with shape[1,48,2,25,566,64] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node sample_sequence/while/concat}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

	 [[sample_sequence/while/Exit_3/_1387]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

  (1) Resource exhausted: OOM when allocating tensor with shape[1,48,2,25,566,64] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node sample_sequence/while/concat}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "play.py", line 271, in <module>
    play_aidungeon_2()
  File "play.py", line 234, in play_aidungeon_2
    result = "\n" + story_manager.act(action)
  File "/content/AIDungeon/AIDungeon/story/story_manager.py", line 207, in act
    result = self.generate_result(action_choice)
  File "/content/AIDungeon/AIDungeon/story/story_manager.py", line 212, in generate_result
    block = self.generator.generate(self.story_context() + action)
  File "/content/AIDungeon/AIDungeon/generator/gpt2/gpt2_generator.py", line 119, in generate
    text = self.generate_raw(prompt)
  File "/content/AIDungeon/AIDungeon/generator/gpt2/gpt2_generator.py", line 102, in generate_raw
    self.context: [context_tokens for _ in range(self.batch_size)]
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: 2 root error(s) found.
  (0) Resource exhausted: OOM when allocating tensor with shape[1,48,2,25,566,64] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[node sample_sequence/while/concat (defined at /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py:1748) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

	 [[sample_sequence/while/Exit_3/_1387]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

  (1) Resource exhausted: OOM when allocating tensor with shape[1,48,2,25,566,64] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[node sample_sequence/while/concat (defined at /usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py:1748) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

0 successful operations.
0 derived errors ignored.

Original stack trace for 'sample_sequence/while/concat':
  File "play.py", line 271, in <module>
    play_aidungeon_2()
  File "play.py", line 106, in play_aidungeon_2
    generator = GPT2Generator()
  File "/content/AIDungeon/AIDungeon/generator/gpt2/gpt2_generator.py", line 51, in __init__
    top_p=top_p,
  File "/content/AIDungeon/AIDungeon/generator/gpt2/src/sample.py", line 120, in sample_sequence
    back_prop=False,
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/control_flow_ops.py", line 2753, in while_loop
    return_same_structure)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/control_flow_ops.py", line 2245, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/control_flow_ops.py", line 2170, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/control_flow_ops.py", line 2705, in <lambda>
    body = lambda i, lv: (i + 1, orig_body(*lv))
  File "/content/AIDungeon/AIDungeon/generator/gpt2/src/sample.py", line 98, in body
    else tf.concat([past, next_outputs["presents"]], axis=-2),
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/array_ops.py", line 1420, in concat
    return gen_array_ops.concat_v2(values=values, axis=axis, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/ops/gen_array_ops.py", line 1257, in concat_v2
    "ConcatV2", values=values, axis=axis, name=name)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()

**Comment by louisgv** [comment]
Yeah you are just out of memory. The program ran fine. If you would like a smoother experience, feel free to support the project's patreon: https://www.patreon.com/AIDungeon 

The proceed should help with the release of the app.

**Comment by ben-bay** [comment]
Congrats for understanding our bad UI and setting it up correctly!
