### ISSUE TITLE
[BUG] custom game crashes

### ISSUE THREAD

**Issue by deepbluesea** [AIDungeon/AIDungeon#188]
## 🐛 Bug Report

**Describe the bug**
ValueError: not enough values to unpack (expected 5, got 2)

```
Starting Prompt: you are a man shopping at walmart and a crazy man with a gun starts pointing it at people and threatens to shoot people unless they throw their wallet on the floor
Traceback (most recent call last):
  File "play.py", line 359, in <module>
    play_aidungeon_2()
  File "play.py", line 178, in play_aidungeon_2
    setting_key, character_key, name, character, setting_description = select_game()
ValueError: not enough values to unpack (expected 5, got 2)
```

**Comment by ben-bay** [comment]
Thanks, this should be resolved with PR #186
