### ISSUE TITLE
ValueError: Can't load save_path when it is None.

### ISSUE THREAD

**Issue by drandreaskrueger** [AIDungeon/AIDungeon#38]
https://colab.research.google.com/github/nickwalton/AIDungeon/blob/master/AIDungeon_2.ipynb
```
Download Complete!
```
but then

```
AI Dungeon 2 will save and use your actions and game to continually improve AI
 Dungeon. If you would like to disable this enter 'nosaving' for any action.
 This will also turn off the ability to save games.

Initializing AI Dungeon! (This might take a few minutes)

ERROR:tensorflow:Couldn't match files for checkpoint generator/gpt2/models/model_v5/model-550
Traceback (most recent call last):
  File "play.py", line 211, in <module>
    play_aidungeon_2()
  File "play.py", line 74, in play_aidungeon_2
    generator = GPT2Generator()
  File "/content/AIDungeon/generator/gpt2/gpt2_generator.py", line 49, in __init__
    saver.restore(self.sess, ckpt)
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_core/python/training/saver.py", line 1277, in restore
    raise ValueError("Can't load save_path when it is None.")
ValueError: Can't load save_path when it is None.
```

**Comment by drandreaskrueger** [comment]
version:

```
!git clone --depth 1 --branch master https://github.com/nickwalton/AIDungeon/
%cd AIDungeon
!git log
```
says

```
commit 75f6379039018cba719c05b7fd6216f1f34274d2 (grafted, HEAD -> master, origin/master, origin/HEAD)
Author: Nick Walton <nickwalton00@gmail.com>
Date:   Sat Dec 7 16:31:30 2019 -0700
...
```

**Comment by nickwalton** [comment]
Should be fixed now. Let me know if it isn't

**Comment by nickwalton** [comment]
Nevermind. Is not fixed. Download costs got too expensive so temporarily shutting down bucket access.

**Comment by drandreaskrueger** [comment]
Thanks a lot.

Looks like you switched to torrent now? All this works well:

```
Cloning into 'AIDungeon'... remote: Enumerating objects: 47, done.
...
Downloading AIDungeon2 Model... (this may take a very, very long time)
... We are now starting to download the model. It will take a while to get up to speed. 
DHT errors are normal.
...

Download Complete!
```
Yes, there was 1 DHT error (Why not catch it and call it something else than a red ERROR?)

And then:

```
AI Dungeon 2 will save and use your actions and game to continually improve AI
 Dungeon. If you would like to disable this enter 'nosaving' for any action.
 This will also turn off the ability to save games.

Initializing AI Dungeon! (This might take a few minutes)

```

```
Generating story...

You are Andreas, a wizard living in the kingdom of Larion. You have a staff and
 a spellbook. You finish your long journey and finally arrive at the ruin you've
 been looking for. You look around and see that it's not much different than
 when you left it.
As you walk through the ruins, you hear voices behind you. It's another group
 of people who want to know what happened to you
```

Well done, all good. 

Thank you very much!

CanClose!
