### ISSUE TITLE
Error handling for story_manager

### ISSUE THREAD

**Issue by zcanann** [AIDungeon/AIDungeon#40]
Error handling needs some beefing up in this class. Loading a non-existing file causes a crash (in `load_from_local`)

Another suggestion: Allow loading a save game on the "pick a setting" screen, instead of waiting for the user to boot into a new game first.

Also it seems to default to doing a cloud save? Perhaps some sort of fail-over to local storage?

Crash output:
`Traceback (most recent call last):
  File ".\play.py", line 222, in <module>
    play_aidungeon_2()
  File ".\play.py", line 131, in play_aidungeon_2
    id = story_manager.story.save_to_storage()
  File "C:\Users\zcanann\source\repos\AIDungeon\story\story_manager.py", line 131, in save_to_storage
    p = Popen(['gsutil', 'cp', file_name, 'gs://aidungeonstories'], stdout=FNULL, stderr=subprocess.STDOUT)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1520.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1520.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified
Exception ignored in: <function Story.__del__ at 0x000001E61E3BEAF8>
Traceback (most recent call last):
  File "C:\Users\zcanann\source\repos\AIDungeon\story\story_manager.py", line 35, in __del__
    self.save_to_storage()
  File "C:\Users\zcanann\source\repos\AIDungeon\story\story_manager.py", line 131, in save_to_storage
    p = Popen(['gsutil', 'cp', file_name, 'gs://aidungeonstories'], stdout=FNULL, stderr=subprocess.STDOUT)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1520.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 800, in __init__
    restore_signals, start_new_session)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.7_3.7.1520.0_x64__qbz5n2kfra8p0\lib\subprocess.py", line 1207, in _execute_child
    startupinfo)
FileNotFoundError: [WinError 2] The system cannot find the file specified`

**Comment by ben-bay** [comment]
PR #61 is looking to add your second suggestion. What do you think of it?

**Comment by zcanann** [comment]
Looks good! Much appreciated.
