### ISSUE TITLE
Error on starting it.

### ISSUE THREAD

**Issue by attbon** [AIDungeon/AIDungeon#43]
It worked yesterday, but trying to start it today gives me this:

Initializing AI Dungeon! (This might take a few minutes)

Traceback (most recent call last):
  File "play.py", line 211, in <module>
    play_aidungeon_2()
  File "play.py", line 74, in play_aidungeon_2
    generator = GPT2Generator()
  File "/content/AIDungeon/generator/gpt2/gpt2_generator.py", line 27, in __init__
    self.enc = encoder.get_encoder(self.model_name, models_dir)
  File "/content/AIDungeon/generator/gpt2/src/encoder.py", line 109, in get_encoder
    with open(os.path.join(models_dir, model_name, 'encoder.json'), 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'generator/gpt2/models/model_v5/encoder.json'

**Comment by JushBJJ** [comment]
https://github.com/nickwalton/AIDungeon/issues/39

**Comment by ben-bay** [comment]
Closing due to duplicate issue #39 .
