### ISSUE TITLE
[BUG] gsutil not found

### ISSUE THREAD

**Issue by godofgrunts** [AIDungeon/AIDungeon#83]
**Describe the bug**

**To Reproduce**
Not sure, I was a few hours into my game and I issued `sit on throne` and the game crashed.

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1365, in _do_call
    return fn(*args)
  File "/usr/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
  File "/usr/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[0,0] = 1024 is not in [0, 1024)
	 [[{{node sample_sequence/while/model/GatherV2_1}}]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "./play.py", line 261, in <module>
    play_aidungeon_2()
  File "./play.py", line 224, in play_aidungeon_2
    result = "\n" + story_manager.act(action)
  File "/mnt/data/AIDungeon/story/story_manager.py", line 206, in act
    result = self.generate_result(action_choice)
  File "/mnt/data/AIDungeon/story/story_manager.py", line 211, in generate_result
    block = self.generator.generate(self.story_context() + action)
  File "/mnt/data/AIDungeon/generator/gpt2/gpt2_generator.py", line 116, in generate
    text = self.generate_raw(prompt)
  File "/mnt/data/AIDungeon/generator/gpt2/gpt2_generator.py", line 99, in generate_raw
    self.context: [context_tokens for _ in range(self.batch_size)]
  File "/usr/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 956, in run
    run_metadata_ptr)
  File "/usr/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1180, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1359, in _do_run
    run_metadata)
  File "/usr/lib/python3.6/site-packages/tensorflow_core/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: indices[0,0] = 1024 is not in [0, 1024)
	 [[node sample_sequence/while/model/GatherV2_1 (defined at /usr/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1748) ]]

Original stack trace for 'sample_sequence/while/model/GatherV2_1':
  File "./play.py", line 261, in <module>
    play_aidungeon_2()
  File "./play.py", line 102, in play_aidungeon_2
    generator = GPT2Generator()
  File "/mnt/data/AIDungeon/generator/gpt2/gpt2_generator.py", line 49, in __init__
    top_p=top_p,
  File "/mnt/data/AIDungeon/generator/gpt2/src/sample.py", line 121, in sample_sequence
    back_prop=False,
  File "/usr/lib/python3.6/site-packages/tensorflow_core/python/ops/control_flow_ops.py", line 2753, in while_loop
    return_same_structure)
  File "/usr/lib/python3.6/site-packages/tensorflow_core/python/ops/control_flow_ops.py", line 2245, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/usr/lib/python3.6/site-packages/tensorflow_core/python/ops/control_flow_ops.py", line 2170, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/usr/lib/python3.6/site-packages/tensorflow_core/python/ops/control_flow_ops.py", line 2705, in <lambda>
    body = lambda i, lv: (i + 1, orig_body(*lv))
  File "/mnt/data/AIDungeon/generator/gpt2/src/sample.py", line 90, in body
    next_outputs = step(hparams, prev, past=past)
  File "/mnt/data/AIDungeon/generator/gpt2/src/sample.py", line 76, in step
    hparams=hparams, X=tokens, past=past, reuse=tf.AUTO_REUSE
  File "/mnt/data/AIDungeon/generator/gpt2/src/model.py", line 185, in model
    h = tf.gather(wte, X) + tf.gather(wpe, positions_for(X, past_length))
  File "/usr/lib/python3.6/site-packages/tensorflow_core/python/util/dispatch.py", line 180, in wrapper
    return target(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/tensorflow_core/python/ops/array_ops.py", line 3956, in gather
    params, indices, axis, name=name)
  File "/usr/lib/python3.6/site-packages/tensorflow_core/python/ops/gen_array_ops.py", line 4082, in gather_v2
    batch_dims=batch_dims, name=name)
  File "/usr/lib/python3.6/site-packages/tensorflow_core/python/framework/op_def_library.py", line 794, in _apply_op_helper
    op_def=op_def)
  File "/usr/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3357, in create_op
    attrs, op_def, compute_device)
  File "/usr/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 3426, in _create_op_internal
    op_def=op_def)
  File "/usr/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py", line 1748, in __init__
    self._traceback = tf_stack.extract_stack()

Exception ignored in: <bound method Story.__del__ of <story.story_manager.Story object at 0x7f3b70f93dd8>>
Traceback (most recent call last):
  File "/mnt/data/AIDungeon/story/story_manager.py", line 37, in __del__
    self.save_to_storage()
  File "/mnt/data/AIDungeon/story/story_manager.py", line 135, in save_to_storage
    stderr=subprocess.STDOUT,
  File "/usr/lib/python3.6/subprocess.py", line 729, in __init__
    restore_signals, start_new_session)
  File "/usr/lib/python3.6/subprocess.py", line 1364, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'gsutil': 'gsutil'
```

**Expected behavior**
The game doesn't crash.

I think you just need to add `gsutil` to `requirements.txt`

**Additional context**
- OS, environment
- Arch Linux, python3.6
- Game settings
- Fantasy, Wizard

**Comment by ben-bay** [comment]
Thanks for catching this, I am adding it to `requirements.txt`.
